"""
Tests for the general document ingestion pipeline.

Covers all four components:
  1. general_parser  -- prose, table, and image extraction
  2. general_chunker -- paragraph-aware chunking with overlap
  3. general_validator -- sanity checks for unstructured text
  4. ingest_general  -- end-to-end pipeline, isolation from fault-code index

Uses a synthetic 3-page PDF fixture (tests/fixtures/test_manual.pdf).
"""
import hashlib
import json
from pathlib import Path

import pytest

# Fixture PDF path (generated by tests/fixtures/_build_fixture.py)
FIXTURE_DIR = Path(__file__).parent / "fixtures"
FIXTURE_PDF = FIXTURE_DIR / "test_manual.pdf"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fixture_hash() -> str:
    h = hashlib.sha256()
    with open(FIXTURE_PDF, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# 1. Parser tests
# ---------------------------------------------------------------------------

class TestGeneralParser:
    """Test app.ingestion.general_parser."""

    def test_parse_returns_items(self):
        """Parser extracts content items from the fixture PDF."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        items = result["items"]
        assert len(items) > 0
        assert result["source_hash"] == _fixture_hash()
        assert result["source_document"] == FIXTURE_PDF.name
        assert result["page_count"] == 3

    def test_prose_extracted(self):
        """Prose text is captured with page numbers."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        prose_items = [i for i in result["items"] if i["type"] == "prose"]
        assert len(prose_items) >= 2  # page 1 and page 2 have prose

        # Check page 1 prose content
        p1 = [i for i in prose_items if i["page_number"] == 1]
        assert len(p1) >= 1
        assert "General Information" in p1[0]["text"]

    def test_table_extracted(self):
        """Table on page 3 is detected and extracted."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        table_items = [i for i in result["items"] if i["type"] == "table"]
        assert len(table_items) >= 1

        t = table_items[0]
        assert t["page_number"] == 3
        # Table should have header + data rows
        assert len(t["data"]) >= 2
        # Header should contain expected column names
        header = t["data"][0]
        assert any("Fastener" in str(c) for c in header)

    def test_page_numbers_captured(self):
        """Every content item has a page_number."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        for item in result["items"]:
            if item["type"] != "image":
                assert "page_number" in item
                assert item["page_number"] is not None

    def test_image_extracted(self):
        """Embedded image on page 2 is extracted."""
        import fitz

        # Only test if the fixture has an embedded image
        with fitz.open(str(FIXTURE_PDF)) as doc:
            has_img = any(doc[1].get_images(full=True))
        if not has_img:
            pytest.skip("Fixture has no embedded image")

        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        image_items = [i for i in result["items"] if i["type"] == "image"]
        assert len(image_items) >= 1

        img = image_items[0]
        assert img["page_number"] == 2
        assert img["image_file_path"]  # not empty

    def test_image_caption_detected(self):
        """Caption text near the image is captured."""
        import fitz

        with fitz.open(str(FIXTURE_PDF)) as doc:
            has_img = any(doc[1].get_images(full=True))
        if not has_img:
            pytest.skip("Fixture has no embedded image")

        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        image_items = [i for i in result["items"] if i["type"] == "image"]
        assert len(image_items) >= 1
        assert image_items[0].get("caption") is not None

    def test_section_headings_detected(self):
        """Chapter headings are detected as section headings."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        prose_items = [i for i in result["items"] if i["type"] == "prose"]
        headings = [
            i.get("section_heading")
            for i in prose_items
            if i.get("section_heading")
        ]
        assert len(headings) >= 1

    def test_file_not_found_raises(self):
        """Parser raises FileNotFoundError for missing PDF."""
        from app.ingestion.general_parser import parse_general_pdf

        with pytest.raises(FileNotFoundError):
            parse_general_pdf(Path("/nonexistent/file.pdf"))

    def test_source_hash_is_sha256(self):
        """Source hash matches the SHA-256 of the PDF file."""
        from app.ingestion.general_parser import parse_general_pdf

        result = parse_general_pdf(FIXTURE_PDF)
        assert result["source_hash"] == _fixture_hash()
        assert len(result["source_hash"]) == 64  # hex SHA-256

    def test_boilerplate_dedup_removes_repeated_chunks(self):
        """Chunks repeating across many pages are deduplicated."""
        from app.ingestion.general_chunker import (
            deduplicate_boilerplate_chunks,
        )

        boilerplate = (
            "WARNING: Read the owner's manual before operation. "
            "Failure to follow warnings could result in serious injury."
        )
        unique_texts = [
            "The engine oil capacity is 2.9 litres.",
            "Check tire pressure when tires are cold.",
            "Chain slack should be 25-35mm.",
            "Coolant level should be between F and L.",
            "Spark plug gap is 0.7-0.8mm.",
        ]

        def _make_chunk(text, page, ctype="prose"):
            return {
                "chunk_id": f"chunk-{page}-{ctype}",
                "chunk_text": text,
                "document_name": "test.pdf",
                "page_number": page,
                "chunk_type": ctype,
                "token_count": len(text.split()),
                "source_hash": "abc123",
                "section_heading": None,
                "image_file_path": None,
                "figure_references": [],
                "error_code": None,
                "sl_no": None,
                "error_description": None,
                "error_remarks": None,
                "document_version": None,
                "system_name": None,
                "subsystem": None,
                "chapter": None,
                "section": None,
            }

        chunks = []
        # Add boilerplate on 10 different pages (> 6 threshold)
        for page in range(1, 11):
            chunks.append(_make_chunk(boilerplate, page))
        # Add unique prose chunks
        for i, text in enumerate(unique_texts):
            chunks.append(_make_chunk(text, i + 1))
        # Add a table chunk (should never be dropped)
        chunks.append(_make_chunk("A | B\n1 | 2", 6, "table"))

        filtered = deduplicate_boilerplate_chunks(chunks)

        # Boilerplate should appear only once (first occurrence kept)
        bp_count = sum(
            1 for c in filtered
            if c.get("chunk_text") == boilerplate
        )
        assert bp_count == 1, (
            f"Expected 1 boilerplate chunk, got {bp_count}"
        )
        # All unique chunks + 1 boilerplate + 1 table should be preserved
        assert len(filtered) == len(unique_texts) + 1 + 1

    def test_boilerplate_dedup_keeps_non_repeating_chunks(self):
        """Chunks appearing on fewer than 6 pages are kept."""
        from app.ingestion.general_chunker import (
            deduplicate_boilerplate_chunks,
        )

        text = "This warning appears on only 3 pages."
        chunks = [
            {
                "chunk_id": f"chunk-{i}",
                "chunk_text": text,
                "document_name": "test.pdf",
                "page_number": i,
                "chunk_type": "prose",
                "token_count": len(text.split()),
                "source_hash": "abc123",
                "section_heading": None,
                "image_file_path": None,
                "figure_references": [],
                "error_code": None,
                "sl_no": None,
                "error_description": None,
                "error_remarks": None,
                "document_version": None,
                "system_name": None,
                "subsystem": None,
                "chapter": None,
                "section": None,
            }
            for i in range(1, 4)  # only 3 pages < 6 threshold
        ]
        filtered = deduplicate_boilerplate_chunks(chunks)
        assert len(filtered) == len(chunks)


# ---------------------------------------------------------------------------
# 2. Chunker tests
# ---------------------------------------------------------------------------

class TestGeneralChunker:
    """Test app.ingestion.general_chunker."""

    @pytest.fixture
    def parse_result(self):
        from app.ingestion.general_parser import parse_general_pdf
        return parse_general_pdf(FIXTURE_PDF)

    def test_chunks_produced(self, parse_result):
        """Chunker produces at least one chunk from the fixture."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        assert len(chunks) >= 1

    def test_paragraph_boundaries_respected(self, parse_result):
        """Chunks split at paragraph boundaries, not mid-sentence."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        prose_chunks = [c for c in chunks if c["chunk_type"] == "prose"]
        for chunk in prose_chunks:
            text = chunk["chunk_text"]
            # A chunk should not start or end with a partial sentence
            # (very rough heuristic: no chunk starts with a lowercase word
            #  unless it's a continuation from overlap)
            if text:
                # Just verify the chunk is non-empty and reasonable
                assert len(text) > 0

    def test_overlap_present(self, parse_result):
        """Adjacent prose chunks share some text (overlap)."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(
            parse_result, max_tokens=50, overlap_ratio=0.15,
        )
        prose_chunks = [c for c in chunks if c["chunk_type"] == "prose"]
        if len(prose_chunks) < 2:
            pytest.skip("Not enough prose chunks to test overlap")

        # Check that at least one adjacent pair shares words
        found_overlap = False
        for i in range(len(prose_chunks) - 1):
            words_a = set(prose_chunks[i]["chunk_text"].lower().split())
            words_b = set(prose_chunks[i + 1]["chunk_text"].lower().split())
            shared = words_a & words_b
            if len(shared) > 3:
                found_overlap = True
                break
        assert found_overlap, "Expected overlap between adjacent chunks"

    def test_table_stays_intact(self, parse_result):
        """Table content is not split into row-by-row chunks."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        table_chunks = [c for c in chunks if c["chunk_type"] == "table"]
        assert len(table_chunks) >= 1

        # The entire table should be one chunk
        t = table_chunks[0]
        assert "Oil drain plug" in t["chunk_text"]
        assert "Front axle nut" in t["chunk_text"]

    def test_chunk_schema_compatible(self, parse_result):
        """Chunk records have all fields needed for future merge."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        required_fields = [
            "chunk_id", "chunk_text", "document_name", "page_number",
            "chunk_type", "token_count", "source_hash",
            "error_code", "sl_no", "error_description", "error_remarks",
            "section_heading", "image_file_path", "figure_references",
        ]
        for chunk in chunks:
            for field in required_fields:
                assert field in chunk, f"Missing field '{field}' in chunk"

    def test_source_document_set(self, parse_result):
        """Every chunk has document_name set to the PDF filename."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        for chunk in chunks:
            assert chunk["document_name"] == FIXTURE_PDF.name

    def test_token_count_reasonable(self, parse_result):
        """Token counts are positive and not wildly wrong."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        for chunk in chunks:
            assert chunk["token_count"] > 0
            # Sanity: token count should be within 5x of word count
            actual_words = len(chunk["chunk_text"].split())
            assert abs(chunk["token_count"] - actual_words) <= actual_words * 4 + 1

    def test_chunk_ids_unique(self, parse_result):
        """Every chunk gets a unique chunk_id."""
        from app.ingestion.general_chunker import build_general_chunks

        chunks = build_general_chunks(parse_result)
        ids = [c["chunk_id"] for c in chunks]
        assert len(ids) == len(set(ids))

    def test_save_and_load_roundtrip(self, parse_result, tmp_path):
        """Chunks survive save/load roundtrip."""
        from app.ingestion.general_chunker import (
            build_general_chunks,
            load_general_chunks,
            save_general_chunks,
        )

        chunks = build_general_chunks(parse_result)
        out_path = tmp_path / "chunks.jsonl"
        save_general_chunks(chunks, out_path)
        loaded = load_general_chunks(out_path)

        assert len(loaded) == len(chunks)
        for orig, load in zip(chunks, loaded):
            assert orig["chunk_id"] == load["chunk_id"]
            assert orig["chunk_text"] == load["chunk_text"]


# ---------------------------------------------------------------------------
# 3. Validator tests
# ---------------------------------------------------------------------------

class TestGeneralValidator:
    """Test app.ingestion.general_validator."""

    def _make_chunk(self, text="Hello world", doc="test.pdf",
                    page=1, ctype="prose"):
        return {
            "chunk_id": "test-id",
            "chunk_text": text,
            "document_name": doc,
            "page_number": page,
            "chunk_type": ctype,
            "token_count": len(text.split()),
            "source_hash": "abc123",
            "section_heading": None,
            "image_file_path": None,
            "figure_references": [],
            "error_code": None,
            "sl_no": None,
            "error_description": None,
            "error_remarks": None,
            "document_version": None,
            "system_name": None,
            "subsystem": None,
            "chapter": None,
            "section": None,
        }

    def test_valid_chunks_pass(self):
        """Normal chunks pass validation."""
        from app.ingestion.general_validator import validate_general_chunks

        chunks = [self._make_chunk(), self._make_chunk("Another chunk")]
        warnings, errors = validate_general_chunks(chunks)
        assert errors == []

    def test_empty_chunk_rejected(self):
        """Empty chunk text produces an error."""
        from app.ingestion.general_validator import validate_general_chunks

        chunks = [self._make_chunk(text="")]
        warnings, errors = validate_general_chunks(chunks)
        assert any("EMPTY" in e for e in errors)

    def test_oversized_chunk_flagged(self):
        """Chunk exceeding MAX_CHUNK_TOKENS produces a warning."""
        from app.ingestion.general_validator import validate_general_chunks

        big_text = "word " * 4000
        chunks = [self._make_chunk(text=big_text)]
        warnings, errors = validate_general_chunks(chunks)
        assert any("OVERSIZE" in w for w in warnings)

    def test_missing_document_rejected(self):
        """Chunk with empty document_name produces an error."""
        from app.ingestion.general_validator import validate_general_chunks

        chunks = [self._make_chunk(doc="")]
        warnings, errors = validate_general_chunks(chunks)
        assert any("MISSING_DOC" in e for e in errors)

    def test_missing_page_warned(self):
        """Chunk with None page_number produces a warning."""
        from app.ingestion.general_validator import validate_general_chunks

        c = self._make_chunk()
        c["page_number"] = None
        warnings, errors = validate_general_chunks([c])
        assert any("NO_PAGE" in w for w in warnings)

    def test_invalid_chunk_type_rejected(self):
        """Chunk with bad chunk_type produces an error."""
        from app.ingestion.general_validator import validate_general_chunks

        c = self._make_chunk()
        c["chunk_type"] = "invalid"
        warnings, errors = validate_general_chunks([c])
        assert any("BAD_TYPE" in e for e in errors)

    def test_duplicate_detected(self):
        """Near-duplicate chunks produce a warning."""
        from app.ingestion.general_validator import validate_general_chunks

        text = "This is a test sentence about motorcycle maintenance"
        c1 = self._make_chunk(text=text)
        c2 = self._make_chunk(text=text + " extra")
        c2["chunk_id"] = "test-id-2"
        warnings, errors = validate_general_chunks([c1, c2])
        assert any("DUPLICATE" in w for w in warnings)

    def test_empty_list_rejected(self):
        """Empty chunk list produces a critical error."""
        from app.ingestion.general_validator import validate_general_chunks

        warnings, errors = validate_general_chunks([])
        assert any("CRITICAL" in e for e in errors)


# ---------------------------------------------------------------------------
# 4. End-to-end ingestion test (isolation from fault-code index)
# ---------------------------------------------------------------------------

class TestIngestGeneral:
    """Test app.ingestion.ingest_general end-to-end."""

    def test_end_to_end_creates_general_index(self, tmp_path):
        """
        Run the full pipeline against the fixture PDF and verify:
        - data/index/general/ is created
        - data/index/faiss.index (existing) is NOT touched
        """
        from unittest.mock import MagicMock, patch

        from app.ingestion.ingest_general import run_general_ingestion

        # Patch the output paths to use tmp_path so we don't touch real data
        import app.ingestion.ingest_general as mod

        general_dir = tmp_path / "general"
        orig_faiss = mod.GENERAL_FAISS_PATH
        orig_chunks = mod.GENERAL_CHUNKS_PATH
        orig_index_dir = mod.GENERAL_INDEX_DIR
        try:
            mod.GENERAL_INDEX_DIR = general_dir
            mod.GENERAL_FAISS_PATH = general_dir / "faiss.index"
            mod.GENERAL_CHUNKS_PATH = general_dir / "chunks.jsonl"

            # Mock the embedder (model not available in CI sandbox)
            mock_embedder = MagicMock()
            # Return a 384-dim vector (matching BGE-small-en-v1.5)
            import numpy as np

            def fake_embed(texts):
                return [np.random.RandomState(42).randn(384).tolist()
                        for _ in texts]
            mock_embedder.embed_documents = fake_embed

            with patch(
                "app.ingestion.ingest_general._embed_chunks",
                side_effect=lambda chunks: np.array(
                    fake_embed([c["chunk_text"] for c in chunks]),
                    dtype=np.float32,
                ),
            ):
                success = run_general_ingestion(FIXTURE_PDF)

            assert success is True

            # Verify index files created
            assert mod.GENERAL_FAISS_PATH.exists()
            assert mod.GENERAL_CHUNKS_PATH.exists()

            # Verify chunks are loadable and have correct source
            with open(mod.GENERAL_CHUNKS_PATH) as f:
                chunks = [json.loads(line) for line in f if line.strip()]
            assert len(chunks) > 0
            for c in chunks:
                assert c["document_name"] == FIXTURE_PDF.name
                assert c["source_hash"] == _fixture_hash()
        finally:
            mod.GENERAL_FAISS_PATH = orig_faiss
            mod.GENERAL_CHUNKS_PATH = orig_chunks
            mod.GENERAL_INDEX_DIR = orig_index_dir

    def test_existing_index_untouched(self, tmp_path):
        """
        Explicitly verify that data/index/faiss.index and
        data/index/chunks.jsonl are never modified by general ingestion.
        """
        from unittest.mock import patch

        import numpy as np

        from app.ingestion.ingest_general import run_general_ingestion
        from app.settings import CHUNKS_STORE_PATH, FAISS_INDEX_PATH

        # Record checksums of existing fault-code index files
        def _hash(p: Path) -> str | None:
            if not p.exists():
                return None
            h = hashlib.sha256()
            with open(p, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            return h.hexdigest()

        faiss_before = _hash(FAISS_INDEX_PATH)
        chunks_before = _hash(CHUNKS_STORE_PATH)

        # Patch output to tmp_path
        import app.ingestion.ingest_general as mod

        general_dir = tmp_path / "general"
        orig_faiss = mod.GENERAL_FAISS_PATH
        orig_chunks = mod.GENERAL_CHUNKS_PATH
        orig_index_dir = mod.GENERAL_INDEX_DIR
        try:
            mod.GENERAL_INDEX_DIR = general_dir
            mod.GENERAL_FAISS_PATH = general_dir / "faiss.index"
            mod.GENERAL_CHUNKS_PATH = general_dir / "chunks.jsonl"

            def fake_embed(chunks):
                rng = np.random.RandomState(42)
                return np.array(
                    [rng.randn(384).tolist() for _ in chunks],
                    dtype=np.float32,
                )

            with patch(
                "app.ingestion.ingest_general._embed_chunks",
                side_effect=fake_embed,
            ):
                run_general_ingestion(FIXTURE_PDF)

            # Verify existing index files are byte-identical
            assert _hash(FAISS_INDEX_PATH) == faiss_before
            assert _hash(CHUNKS_STORE_PATH) == chunks_before
        finally:
            mod.GENERAL_FAISS_PATH = orig_faiss
            mod.GENERAL_CHUNKS_PATH = orig_chunks
            mod.GENERAL_INDEX_DIR = orig_index_dir

    def test_existing_test_suite_unaffected(self):
        """Sanity: the existing fault-code tests still pass."""
        # This is validated by the full test run, but we include an explicit
        # check here for documentation purposes.
        from app.ingestion.chunker import load_chunks
        from app.settings import CHUNKS_STORE_PATH

        if CHUNKS_STORE_PATH.exists():
            chunks = load_chunks(CHUNKS_STORE_PATH)
            assert len(chunks) == 28  # existing fault-code corpus


# ---------------------------------------------------------------------------
# 5. Multi-index retriever tests
# ---------------------------------------------------------------------------

class TestMultiIndexRetriever:
    """Test that the retriever searches both fault-code and general indexes."""

    def _make_chunk_dict(self, text, doc, page, code=None):
        """Minimal chunk dict matching the shared schema."""
        return {
            "chunk_id": f"chunk-{doc}-{page}",
            "chunk_text": text,
            "document_name": doc,
            "page_number": page,
            "chunk_type": "prose",
            "token_count": len(text.split()),
            "source_hash": "abc123",
            "section_heading": None,
            "image_file_path": None,
            "figure_references": [],
            "error_code": code,
            "sl_no": None,
            "error_description": None,
            "error_remarks": None,
            "document_version": None,
            "system_name": None,
            "subsystem": None,
            "chapter": None,
            "section": None,
        }

    def test_retriever_loads_general_index(self, tmp_path):
        """Retriever loads the general index when files exist."""
        import numpy as np
        import faiss

        # Create a minimal general index
        gen_dir = tmp_path / "general"
        gen_dir.mkdir()
        dim = 384
        n = 3
        index = faiss.IndexFlatIP(dim)
        rng = np.random.RandomState(99)
        vecs = rng.randn(n, dim).astype(np.float32)
        faiss.normalize_L2(vecs)
        index.add(vecs)
        faiss.write_index(index, str(gen_dir / "faiss.index"))

        chunks = [
            self._make_chunk_dict("Check tire pressure often", "manual.pdf", 10),
            self._make_chunk_dict("Engine oil capacity 2.9L", "manual.pdf", 20),
            self._make_chunk_dict("Chain slack 25-35mm", "manual.pdf", 30),
        ]
        with open(gen_dir / "chunks.jsonl", "w") as f:
            for c in chunks:
                f.write(json.dumps(c) + "\n")

        # Patch the retriever to use tmp_path for general index
        import app.rag.retriever as mod
        orig_dir = mod._GENERAL_INDEX_DIR
        orig_faiss = mod._GENERAL_FAISS_PATH
        orig_chunks = mod._GENERAL_CHUNKS_PATH
        try:
            mod._GENERAL_INDEX_DIR = gen_dir
            mod._GENERAL_FAISS_PATH = gen_dir / "faiss.index"
            mod._GENERAL_CHUNKS_PATH = gen_dir / "chunks.jsonl"

            r = mod.Retriever()
            assert r._general_index is not None
            assert len(r._general_chunks) == 3
        finally:
            mod._GENERAL_INDEX_DIR = orig_dir
            mod._GENERAL_FAISS_PATH = orig_faiss
            mod._GENERAL_CHUNKS_PATH = orig_chunks

    def test_retriever_works_without_general_index(self):
        """Retriever works normally when general index doesn't exist."""
        import app.rag.retriever as mod

        # Ensure general index paths point to nonexistent location
        orig_dir = mod._GENERAL_INDEX_DIR
        orig_faiss = mod._GENERAL_FAISS_PATH
        orig_chunks = mod._GENERAL_CHUNKS_PATH
        try:
            mod._GENERAL_INDEX_DIR = Path("/nonexistent/general")
            mod._GENERAL_FAISS_PATH = Path("/nonexistent/general/faiss.index")
            mod._GENERAL_CHUNKS_PATH = Path("/nonexistent/general/chunks.jsonl")

            r = mod.Retriever()
            assert r._general_index is None
            assert r._general_chunks == []
            # Should still have the fault-code index
            assert r._index.ntotal > 0
        finally:
            mod._GENERAL_INDEX_DIR = orig_dir
            mod._GENERAL_FAISS_PATH = orig_faiss
            mod._GENERAL_CHUNKS_PATH = orig_chunks
