"""
FastAPI application — serves the web UI and the /query endpoint.

Endpoints:
    GET  /          → index.html (single-page UI)
    POST /query     → RAG pipeline query
    GET  /health    → Ollama + index liveness check
    POST /reload    → hot-reload the FAISS index after re-ingestion

All traffic is loopback-only (127.0.0.1 — PRD Section 12).
No CORS, no remote origins, no telemetry.

State-changing routes (POST /query, POST /reload) are additionally guarded by
a same-origin check — see app/security.py for the threat model (finding S-1).
"""
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
from fastapi import Depends, FastAPI, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from app.logger import get_logger
from app.rag.pipeline import query as rag_query
from app.security import verify_same_origin
from app.settings import FAISS_INDEX_PATH, MODEL_TAG, OLLAMA_URL, SERVER_HOST, SERVER_PORT

log = get_logger(__name__)

STATIC_DIR = Path(__file__).parent / "static"


# ── Lifespan: warm up retriever & embedder on startup ──────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("BEL Offline AI Interface starting …")
    try:
        from app.rag.retriever import get_retriever
        get_retriever()          # loads FAISS index + chunks into memory
        from app.rag.embedder import get_embedder
        get_embedder()           # loads BGE model onto CPU
        log.info("Retriever and embedder ready.")
    except FileNotFoundError as e:
        log.warning("Startup warning: %s", e)
        log.warning("Run ingestion first: python -m app.ingestion.ingest")
    except Exception as e:
        log.error("Startup error: %s", e)
    yield
    log.info("BEL Offline AI Interface shutting down.")


app = FastAPI(
    title="BEL Offline AI — Fault Code Lookup",
    version="1.0.0",
    docs_url=None,       # disable Swagger UI (not needed for this interface)
    redoc_url=None,
    lifespan=lifespan,
)

# Serve static files (CSS, JS) — all local, no CDN
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


# ── Request / Response models ───────────────────────────────────────────────
# Upper bound on an inbound question (finding S-3).
# 2000 chars is ~16x the longest entry in the fault-code corpus (124 chars) and
# far beyond any realistic plain-language lookup, so it never constrains
# legitimate use. Without a bound, an arbitrarily large body is fed straight
# into SentenceTransformer.encode() and then concatenated into the Ollama
# prompt — a cheap local denial of service.
MAX_QUESTION_CHARS = 2000


class QueryRequest(BaseModel):
    # min_length=1 rejects the empty string at the validation layer; the
    # handler additionally strips whitespace-only input, which min_length
    # cannot catch.
    question: str = Field(..., min_length=1, max_length=MAX_QUESTION_CHARS)


class ChunkInfo(BaseModel):
    error_code: str | None
    error_description: str | None
    error_remarks: str | None
    document_name: str | None
    score: float


class QueryResponse(BaseModel):
    answer: str
    citations: list[str]
    retrieved_chunks: list[ChunkInfo]
    top_score: float
    latency_ms: int
    found: bool
    guardrail_triggered: bool
    error: str | None


# ── Routes ──────────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
async def serve_ui():
    index_path = STATIC_DIR / "index.html"
    if not index_path.exists():
        raise HTTPException(status_code=404, detail="UI not found")
    return FileResponse(str(index_path))


@app.get("/favicon.ico", include_in_schema=False)
async def favicon() -> FileResponse:
    """Serve the app favicon so browsers receive 200 instead of a noisy 404."""
    icon_path = STATIC_DIR / "favicon.ico"
    if not icon_path.exists():
        raise HTTPException(status_code=404, detail="favicon.ico not found")
    return FileResponse(str(icon_path), media_type="image/x-icon")


@app.post("/query", response_model=QueryResponse, dependencies=[Depends(verify_same_origin)])
async def query_endpoint(req: QueryRequest):
    """
    Accept a plain-language question and return a grounded answer.
    Every response is generated by the local LLM — never a template (FR-4).
    """
    if not req.question or not req.question.strip():
        raise HTTPException(status_code=422, detail="Question must not be empty.")

    log.info("POST /query | question=%r", req.question[:80])
    result = rag_query(req.question)

    chunks_out = []
    for c in result.retrieved_chunks:
        chunks_out.append(ChunkInfo(
            error_code=c.get("error_code"),
            error_description=c.get("error_description"),
            error_remarks=c.get("error_remarks"),
            document_name=c.get("document_name"),
            score=0.0,   # score stored on RetrievedChunk, not the raw chunk dict
        ))

    return QueryResponse(
        answer=result.answer,
        citations=result.citations,
        retrieved_chunks=chunks_out,
        top_score=round(result.top_score, 4),
        latency_ms=result.latency_ms,
        found=result.found,
        guardrail_triggered=result.guardrail_triggered,
        error=result.error,
    )


@app.get("/health")
async def health():
    """Liveness check — verifies Ollama is reachable and index exists."""
    status = {
        "server": "ok",
        "index_exists": FAISS_INDEX_PATH.exists(),
        "ollama": "unknown",
        "model": MODEL_TAG,
    }
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            r = await client.get(f"{OLLAMA_URL}/api/tags")
            if r.status_code == 200:
                tags = [m["name"] for m in r.json().get("models", [])]
                status["ollama"] = "ok"
                status["model_pulled"] = any(MODEL_TAG in t for t in tags)
            else:
                status["ollama"] = f"http_{r.status_code}"
    except Exception as e:
        # Log the real exception server-side; return only a generic marker.
        # str(e) on httpx/OS errors embeds absolute paths and usernames, and
        # app.js renders this value straight into the chat UI (finding S-2).
        log.error("Ollama health probe failed: %s", e)
        status["ollama"] = "unreachable"

    overall = (
        status["index_exists"]
        and status["ollama"] == "ok"
        and status.get("model_pulled", False)
    )
    status["ready"] = overall
    code = 200 if overall else 503
    return JSONResponse(content=status, status_code=code)


@app.post("/reload", dependencies=[Depends(verify_same_origin)])
async def reload_index():
    """Hot-reload the FAISS index after running the ingestion script."""
    try:
        from app.rag.retriever import get_retriever
        get_retriever().reload()
        return {"status": "ok", "message": "Index reloaded successfully."}
    except Exception as e:
        # Real cause goes to the log only. Returning str(e) would leak the
        # index path and the operator's username to the browser (finding S-2).
        log.error("Reload failed: %s", e, exc_info=True)
        raise HTTPException(
            status_code=500,
            detail="Index reload failed. See the server log for details.",
        )


# ── Entry point ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "app.main:app",
        host=SERVER_HOST,
        port=SERVER_PORT,
        reload=False,
        log_level="info",
    )
