"""
FastAPI application — serves the web UI and the /query endpoint.

Endpoints:
    GET  /          → index.html (single-page UI)
    POST /query     → RAG pipeline query
    GET  /health    → Ollama + index liveness check
    POST /reload    → hot-reload the FAISS index after re-ingestion

All traffic is loopback-only (127.0.0.1 — PRD Section 12).
No CORS, no remote origins, no telemetry.
"""
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from app.logger import get_logger
from app.rag.pipeline import query as rag_query
from app.session import get_session_store
from app.settings import FAISS_INDEX_PATH, MODEL_TAG, OLLAMA_URL, SERVER_HOST, SERVER_PORT

log = get_logger(__name__)

STATIC_DIR = Path(__file__).parent / "static"


# ── Lifespan: warm up retriever & embedder on startup ──────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("BEL Offline AI Interface starting …")
    try:
        from app.rag.retriever import get_retriever
        get_retriever()          # loads FAISS index + chunks into memory
        from app.rag.embedder import get_embedder
        get_embedder()           # loads BGE model onto CPU
        log.info("Retriever and embedder ready.")
    except FileNotFoundError as e:
        log.warning("Startup warning: %s", e)
        log.warning("Run ingestion first: python -m app.ingestion.ingest")
    except Exception as e:
        log.error("Startup error: %s", e)
    yield
    log.info("BEL Offline AI Interface shutting down.")


app = FastAPI(
    title="BEL Offline AI — Fault Code Lookup",
    version="1.0.0",
    docs_url=None,       # disable Swagger UI (not needed for this interface)
    redoc_url=None,
    lifespan=lifespan,
)

# Serve static files (CSS, JS) — all local, no CDN
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


# ── Request / Response models ───────────────────────────────────────────────
class QueryRequest(BaseModel):
    question: str
    session_id: str | None = None


class ChunkInfo(BaseModel):
    error_code: str | None
    error_description: str | None
    error_remarks: str | None
    document_name: str | None
    score: float


class QueryResponse(BaseModel):
    answer: str
    citations: list[str]
    retrieved_chunks: list[ChunkInfo]
    top_score: float
    latency_ms: int
    found: bool
    guardrail_triggered: bool
    error: str | None
    session_id: str | None = None


class ClearSessionRequest(BaseModel):
    session_id: str


# ── Routes ──────────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
async def serve_ui():
    index_path = STATIC_DIR / "index.html"
    if not index_path.exists():
        raise HTTPException(status_code=404, detail="UI not found")
    return FileResponse(str(index_path))


@app.get("/favicon.ico", include_in_schema=False)
async def favicon() -> FileResponse:
    """Serve the app favicon so browsers receive 200 instead of a noisy 404."""
    icon_path = STATIC_DIR / "favicon.ico"
    if not icon_path.exists():
        raise HTTPException(status_code=404, detail="favicon.ico not found")
    return FileResponse(str(icon_path), media_type="image/x-icon")


@app.post("/query", response_model=QueryResponse)
async def query_endpoint(req: QueryRequest):
    """
    Accept a plain-language question and return a grounded answer.
    Every response is generated by the local LLM — never a template (FR-4).
    """
    if not req.question or not req.question.strip():
        raise HTTPException(status_code=422, detail="Question must not be empty.")

    session_id = req.session_id.strip() if (req.session_id and req.session_id.strip()) else str(uuid.uuid4())
    log.info("POST /query | question=%r | session_id=%s", req.question[:80], session_id)
    result = rag_query(req.question, session_id=session_id)

    chunks_out = []
    for c in result.retrieved_chunks:
        chunks_out.append(ChunkInfo(
            error_code=c.get("error_code"),
            error_description=c.get("error_description"),
            error_remarks=c.get("error_remarks"),
            document_name=c.get("document_name"),
            score=0.0,   # score stored on RetrievedChunk, not the raw chunk dict
        ))

    return QueryResponse(
        answer=result.answer,
        citations=result.citations,
        retrieved_chunks=chunks_out,
        top_score=round(result.top_score, 4),
        latency_ms=result.latency_ms,
        found=result.found,
        guardrail_triggered=result.guardrail_triggered,
        error=result.error,
        session_id=session_id,
    )


@app.post("/session/clear")
async def clear_session_endpoint(req: ClearSessionRequest):
    if not req.session_id or not req.session_id.strip():
        raise HTTPException(status_code=422, detail="session_id must not be empty.")
    get_session_store().clear_session(req.session_id)
    return {"status": "ok", "message": f"Cleared history for session {req.session_id}"}



@app.get("/health")
async def health():
    """Liveness check — verifies Ollama is reachable and index exists."""
    status = {
        "server": "ok",
        "index_exists": FAISS_INDEX_PATH.exists(),
        "ollama": "unknown",
        "model": MODEL_TAG,
    }
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            r = await client.get(f"{OLLAMA_URL}/api/tags")
            if r.status_code == 200:
                tags = [m["name"] for m in r.json().get("models", [])]
                status["ollama"] = "ok"
                status["model_pulled"] = any(MODEL_TAG in t for t in tags)
            else:
                status["ollama"] = f"http_{r.status_code}"
    except Exception as e:
        status["ollama"] = f"error: {e}"

    overall = (
        status["index_exists"]
        and status["ollama"] == "ok"
        and status.get("model_pulled", False)
    )
    status["ready"] = overall
    code = 200 if overall else 503
    return JSONResponse(content=status, status_code=code)


@app.post("/reload")
async def reload_index():
    """Hot-reload the FAISS index after running the ingestion script."""
    try:
        from app.rag.retriever import get_retriever
        get_retriever().reload()
        return {"status": "ok", "message": "Index reloaded successfully."}
    except Exception as e:
        log.error("Reload failed: %s", e)
        raise HTTPException(status_code=500, detail=str(e))


# ── Entry point ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "app.main:app",
        host=SERVER_HOST,
        port=SERVER_PORT,
        reload=False,
        log_level="info",
    )
